colorscheme elflord
syntax on

set shiftwidth=4
set tabstop=4

set autoindent
set cindent
set smartindent
set ruler
set number
set sm
set hlsearch
set incsearch
set ignorecase
set filetype=cpp
set backspace=eol,start,indent

map <F5> :w<CR> :!g++ "%" <CR>
map <F6> :!a <CR>

map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>
